### ISSUE TITLE
implement sell/buy

### ISSUE THREAD

**Issue by PRamia** [vijayengineer/Bitcoin_Trading_Bot#2]
very nice solution, just missing how to execute the sell/buy orders there using the saved data.

**Comment by vijayengineer** [comment]
Hi just use the order function. Its already in the code. 
so buy/sell is simply: order(“BUY”, amount, trading_symbol,market_order) and use it with the strategy.
I didn’t include it in the code to keep it generic, and avoid anyone blindly forking the code and losing money. Its still not tested for edge cases.
